mooringlicensing/components/proposals/api.py, mooringlicensing/helpers.py
A proposal could be submitted without any address details - both residential and postal.
If a postal address is not provided, the sticker company will have nowhere to send a printed sticker.
This PR adds address validation. Proposal applications must now include:
- A residential address line 1, town/suburb, state, country, and postcode
- A postal address line 1, town/suburb, state, country, and postcode OR the same as residential address tick box must be ticked
If those details are not provided, the application will remain in the draft stage.
=> Proposal Address Validation

mooringlicensing/frontend/mooringlicensing/src/components/common/vessels.vue, mooringlicensing/frontend/mooringlicensing/src/components/external/dcv/dcv_admission.vue, mooringlicensing/frontend/mooringlicensing/src/components/external/dcv/dcv_permit.vue
On all applications forms where vessel registration can be searched, if a user selects a vessel registration that is not new and that they do not own they will be notified and then the search value will be removed.
Before, the vessel registration would be selectable and remain displayed as though the selection were valid, but the actual underlying value would not be set - this could lead to some confusion when the user receives an error informing them that no vessel has been set. 
Another problem is that if a legitimate vessel registration were set and then replaced with an invalid one - it would appear that the invalid registration would be submitted when the actual value would be that of the initially entered registration. Meaning a user could submit a registration value that they did …
=> Vessel form adjustments

mooringlicensing/components/approvals/models.py, mooringlicensing/components/payments_ml/views.py, mooringlicensing/components/proposals/api.py, mooringlicensing/components/proposals/models.py, mooringlicensing/components/proposals/serializers.py, mooringlicensing/components/proposals/utils.py, mooringlicensing/frontend/mooringlicensing/src/components/common/current_vessels.vue, mooringlicensing/frontend/mooringlicensing/src/components/common/mooring.vue, mooringlicensing/frontend/mooringlicensing/src/components/common/mooring_authorisation.vue, mooringlicensing/frontend/mooringlicensing/src/components/common/table_approvals.vue, mooringlicensing/frontend/mooringlicensing/src/components/common/table_stickers.vue, mooringlicensing/frontend/mooringlicensing/src/components/external/proposal.vue, mooringlicensing/frontend/mooringlicensing/src/components/form_aua.vue, mooringlicensing/frontend/mooringlicensing/src/components/form_mla.vue, mooringlicensing/frontend/mooringlicensing/src/components/form_wla.vue, mooringlicensing/frontend/mooringlicensing/src/components/internal/proposals/proposal.vue, mooringlicensing/helpers.py
Existing Auto-Approve functions have been re-created in python on the server-side based on client-side vue/js functions. Decision to auto-approve an application will no longer be determined on the client-side where it can be potentially manipulated.
Stickers will now be set to expired (subject to their current status) when an approval is set to expired.
Various minor errors have also been fixed:
- potentially infinite while loop fixed
- sticker and approval search fixed
- misapplied vessel ownership error(s) fixed
=> Server-side auto-approve, Sticker Expiry

mooringlicensing/components/proposals/models.py
Added validation step to ensure a vessel can only be owned by one "vessel owner" at a time.
This fixes a reported issue where a WLA was being put through with a vessel already owned by another user.
=> Vessel owner submit validation

mooringlicensing/components/proposals/api.py
When submitting a WLA for an applicant, the submitter id was being incorrectly used to check if the user could submit a wla -  that is now fixed.
=> Fixed internal wla-allowed check

mooringlicensing/components/payments_ml/views.py, mooringlicensing/components/proposals/api.py, mooringlicensing/components/proposals/models.py, mooringlicensing/components/proposals/serializers.py, mooringlicensing/components/proposals/utils.py, mooringlicensing/frontend/mooringlicensing/src/components/common/vessels.vue
Some fixes to auto-approve checks
Fixed status update for auto-approved AUPs that have not been paid for yet (remain in draft until paid)
Added distinct check on vessel owner owners for percentage validation
Disabled single owner restriction (though only one owner can have active approvals still
=> Workflow adjustments/fixes

mooringlicensing/components/approvals/models.py, mooringlicensing/components/payments_ml/models.py, mooringlicensing/components/proposals/api.py, mooringlicensing/components/proposals/models.py, mooringlicensing/components/proposals/serializers.py, mooringlicensing/components/proposals/utils.py, mooringlicensing/frontend/mooringlicensing/src/components/common/vessels.vue
- Vessel ownership listings now only show latest (i.e. relevant) instance (instead displaying the same vessel-owner pairs multiple times)
- WLA (and MLA) no longer require a vessel to be submitted (but are still subject to approval restrictions)
- Users can now look up vessels owned by other users (pii withheld) in case joint ownership is possible
- AUPs must now have at least one mooring to be approved
And minor bug fixes and workflow adjustments as needed
=> Miscellaneous Fixes and Adjustments

mooringlicensing/components/approvals/api.py, mooringlicensing/components/approvals/models.py, mooringlicensing/components/approvals/signals.py, mooringlicensing/components/payments_ml/views.py, mooringlicensing/components/proposals/models.py, mooringlicensing/components/proposals/utils.py, mooringlicensing/frontend/mooringlicensing/src/components/common/table_stickers.vue, mooringlicensing/templates/mooringlicensing/base.html
When an AAA amendment is made before a sticker is printed, the original proposal will now be properly updated when the old sticker is printed. Said old sticker cannot be recorded as returned until printed (or lost). 
AAA auto approval now actually works, skipping the assessor stage when the relevant conditions are met - for amendments and renewals only. Stickers handling is still handled based on the amendment/renewal changes.
Some changes to sticker handling may also correct behaviours for other application types, and will be tested.
=> AAA printing and auto approval adjustments

mooringlicensing/components/approvals/api.py, mooringlicensing/components/approvals/models.py, mooringlicensing/components/proposals/api.py, mooringlicensing/components/proposals/models.py, requirements.txt
Number of changes to ensure proposal statuses are updated properly for MLAs.
Includes:
- proper support for adding more vessels to a ML (before additional stickers were not being printed)
- ensuring statuses are properly handled if a printer is still being printed (users can make amendments while stickers are still being printed)
- allowing users to make multiple amendments while previous amendments are still printing sticker
- ensuring proposals are not approvable (but can still be submitted) until existing sticker records are exported
Changes have been tested for amendments, additional testing/changes for renewals will need to be conducted later on.
=> MLA workflow and sticker process adjustments

mooringlicensing/components/approvals/api.py, mooringlicensing/components/approvals/models.py, mooringlicensing/components/proposals/models.py, requirements.txt
Adjustments to AUP amendment printing workflow to ensure proposals are not left in an invalid status and that the process can be complete for all scenarios.
Also, gunicorn upgrade.
=> AUP printing adjustments

mooringlicensing/components/main/admin.py, mooringlicensing/components/main/models.py, mooringlicensing/components/payments_ml/admin.py
Some model and admin functions try to check the "is_editable" property of certain model instances. Now checking if the instance and/or the pk of the instance exists first to prevent error.
=> Instance and/or PK check 

mooringlicensing/components/proposals/models.py
Overhauled vessel ownership check function - should now be easier to read and maintain, and now follows the business requirements.
Through this some bugs to do with ownership/proposal/approval checks have been fixed. Some previously unimplemented check - such as existing AUPs and MLs blocking new AAAs - have been brought in.
Null vessels are not allowed in all new applications again, but amendments and renewals on most applications can have null vessels.
=> Vessel Ownership, Proposal, and Approval Rules

mooringlicensing/components/proposals/api.py, mooringlicensing/components/proposals/email.py, mooringlicensing/components/proposals/models.py, mooringlicensing/components/proposals/serializers.py, mooringlicensing/frontend/mooringlicensing/src/components/common/workflow.vue, mooringlicensing/frontend/mooringlicensing/src/components/internal/proposals/proposal.vue
Authorised User Applications awaiting endorsement can now be forwarded to the with assessor stage via a bypass endorsement action.
They can also be put back to awaiting endorsement by assessors if any remaining mooring requests have yet to be actioned by an endorser.
Currently approvers can still select/deselect mooring requests - something to be reviewed and potentially removed (alongside other similar controls).
=> AUA endorsement workflow controls

mooringlicensing/components/proposals/api.py, mooringlicensing/components/proposals/models.py, mooringlicensing/components/proposals/utils.py, mooringlicensing/frontend/mooringlicensing/src/components/common/mooring_authorisation.vue, mooringlicensing/frontend/mooringlicensing/src/components/internal/proposals/proposal.vue, mooringlicensing/frontend/mooringlicensing/src/components/internal/proposals/proposed_issuance.vue
After review and changes Approvers:
- can no longer edit an application (and an application cannot be edited once "with approver")
- change the requested moorings of an application
- endorse/decline mooring requests on an endorsers behalf
Assessors can still do all of the above while with the appropriate processing_status.
Approvers can still create applications on a user's behalf, but cannot modifying/submit the application after (which assessors can still do)
=> Approver controls review

mooringlicensing/components/proposals/api.py, mooringlicensing/components/users/utils.py, mooringlicensing/frontend/mooringlicensing/src/components/common/applicant.vue, mooringlicensing/frontend/mooringlicensing/src/components/common/table_proposals.vue, mooringlicensing/frontend/mooringlicensing/src/components/common/vessels.vue, mooringlicensing/frontend/mooringlicensing/src/components/internal/proposals/proposal.vue, mooringlicensing/frontend/mooringlicensing/src/components/user/profile.vue, mooringlicensing/utils/mooring_licence_migrate_pd.py, requirements.txt
Changes to migration script for mooring licensing to account for:
- System User accounts and related required changes
- Inclusion of sticker addresses
- Adjustments to AUA that allow multiple moorings on a single application
System user accounts are now created alongside new and existing ledger accounts. 
System user addresses are added to their respective user accounts, while their ledger account addresses are no longer updated.
Creation of proposal applicant records have been adjusted to account for the related system user changes.
All instances of sticker creation have been adapted to include the postal address of their respective applicant.
Migration script now creates an instance of the site licensee mooring request model per the AUA changes allowing for multiple moorings - note …
=> Realign Migration Script

mooringlicensing/components/payments_ml/utils.py, mooringlicensing/settings.py
Before fee items would be rounded only in debug mode - also they wouldn't have an actual round operation applied, but a ceiling operation (i.e. always rounding up, no matter the value).
Now fee items will be rounded based on their own env var ROUND_FEE_ITEMS (bool) and they use the actual round operation (>=.5 rounded up, <.5 rounded down)
=> Env var for fee item rounding

mooringlicensing/components/approvals/api.py, mooringlicensing/components/proposals/email.py, mooringlicensing/components/proposals/serializers.py, mooringlicensing/components/proposals/utils.py, mooringlicensing/utils/mooring_licence_migrate_pd.py
Some old ledger email addresses are stored with capitalisation.
To accommodate this, all queries using email addresses as a filter or get value now use iexact, which is case insensitive.
Also fixed an incorrectly applied permission on Dcv Admissions viewset.
=> Email query update

mooringlicensing/components/approvals/api.py, mooringlicensing/components/approvals/models.py, mooringlicensing/components/approvals/serializers.py, mooringlicensing/components/compliances/api.py, mooringlicensing/components/proposals/api.py, mooringlicensing/components/proposals/models.py, mooringlicensing/components/proposals/serializers.py, mooringlicensing/components/proposals/utils.py, mooringlicensing/frontend/mooringlicensing/src/components/common/table_approvals.vue, mooringlicensing/frontend/mooringlicensing/src/components/common/table_compliances.vue, mooringlicensing/frontend/mooringlicensing/src/components/common/table_proposals.vue, mooringlicensing/management/commands/approval_renewal_notices.py
Number of fixes for found and reported issues:
- various dashboard table numbers fixed to display accurate values
- fixed error caused by a mooring license not having a mooring (e.g. mid-swap)
- added ordering to applicant/holder columns
- added searching for approval vessel rego numbers
- removed ordering from approval vessel rego numbers
- fixed problem where Annual Admission Permits vessels would inherit the sale date of the previous ownership record
- fixed an issue with renewal management script that would break renewal process if at least one record fails
- fixed a number of additional ordering/searching issues
=> Misc fixes

mooringlicensing/components/proposals/email.py, mooringlicensing/components/proposals/models.py, mooringlicensing/management/commands/approval_renewal_notices.py, mooringlicensing/management/commands/expire_application_due_to_no_payment.py, mooringlicensing/management/commands/expire_mooring_licence_application_due_to_no_documents.py, mooringlicensing/management/commands/expire_mooring_licence_application_due_to_no_submit.py, mooringlicensing/management/commands/send_application_payment_due_reminder.py, mooringlicensing/management/commands/send_compliance_reminder.py, mooringlicensing/management/commands/send_endorser_reminder.py, mooringlicensing/management/commands/send_mooring_licence_application_submit_due_reminder.py, mooringlicensing/management/commands/send_reminder_submission_of_mla.py, mooringlicensing/management/commands/send_vessel_nominate_reminder.py, mooringlicensing/management/commands/update_compliance_status.py
all number of day type settings queries change to use filter first instead of get
=> Number of Day Type Settings Update

mooringlicensing/components/payments_ml/models.py, mooringlicensing/components/payments_ml/views.py, mooringlicensing/components/proposals/models.py, mooringlicensing/components/proposals/serializers.py, mooringlicensing/components/proposals/utils.py, mooringlicensing/utils/mooring_licence_migrate_pd.py
Changes when the Vessel and VesselOwnership instances are created during the application workflow.
They now are created on the application's approval, instead of submission. This means that declined or otherwise cancelled applications will no longer permanently alter any existing Vessel record. 
A number of changes have been made to accommodate the workflow adjustments, including:
- proposal vessel ownership validation checks at the submission and approval stages
- vessel ownership percentage checks
- proposal fee calculation
- vessel details acquisition
=> Vessel save change

mooringlicensing/management/commands/approval_renewal_notices.py, mooringlicensing/settings.py, python-cron
Approval Renewal Notices management command will now only send a maximum of 5 (configurable) renewal notices per relevant approval type (4).
The cron job for it is now set to run every 4 minutes.
=> max number of renewal notices per application

mooringlicensing/components/proposals/models.py
There was a problem with new WLA and AUA proposals not being accepted on the basis of vessel registration number already been in use when they actually were not.
Investigation revealed that the blocking approvals check included approvals with proposals where the vessel ownership fields were set to None. Because new proposals also have vessel ownership fields set to None, effectively any approved proposal with no vessel ownership would render all application unable to be submitted.
This would not usually be a problem as all approved proposals should have vessel ownership set, however an exception to this has occurred on UAT. This PR fixes the validation query to only retrieve approved proposals with vessel ownerships set (using the rego_no otherwise) to allow submissions even after the …
=> Submission fix

.devcontainer/devcontainer.json, mooringlicensing/components/payments_ml/models.py, mooringlicensing/components/proposals/models.py, mooringlicensing/components/proposals/utils.py
Fixes missing ownership for certain applications.
After investigation it was found that auto-approved amendments to AUAs (and MLAs) were missing the required logic to generate vessel ownership records, as that logic was only present during the approval process. Because AUPs and MLAs are usually paid for post-approval, they did not logic to generate vessels after payment. 
Now auto approval is checked post-payment for these application types so that they generated vessel ownership data the same as if approved normally.
=> Missing ownership

mooringlicensing/components/proposals/api.py, mooringlicensing/components/proposals/models.py, mooringlicensing/components/proposals/utils.py
Denies auto approval to MLA, WLA, and AUA where the vessel length category of the provided vessel length is different to the vessel length on record. 
Prior to this auto approval would only be denied if the applicant would have to pay more, typically only if an amendment submitted a vessel length higher than all previous submissions for a given license. Now auto approval is blocked regardless of increased payment, and even when the submitted length is in a length lower category.
Note that the submitted vessel length is compared to most recent prior submission of the vessel with the same rego no (not necessarily the last submission for the given license).
=> Auto Approve Vessel Cat Change

mooringlicensing/components/main/utils.py
Work on sanitisation functions
Script tag removal function, run for all fields including those exclude from full sanitisation, now also check for blacklisted attributes (anything that can run javascript e.g. onclick)
Excluded fields can also have json sub-fields specified for sanitisation exception (script tags and blacklisted attrs still removed)
Sub-fields that need to excluded can be done so by including the parent in the exclude_sanitise and the child attached to that parent with dot notation. Children included will be excluded from dict or lists of dicts.
For example, an exclusion list with ["test_field", "test_field.test_sub_field"] will now exempt any dict with the key test_sub_field assign to a dict named test_field or a dict in list named test_field.
Note: these changes should …
=> Sanitise Additions

mooringlicensing/components/approvals/models.py, mooringlicensing/components/proposals/models.py
AUPs are properly removed from moorings prior to a swap being finalised
A mooring license can no longer be approved (for an amendment, renewal, or swap) if it has an AUP with a sticker that has not been exported
=> AU summary gen fix

mooringlicensing/components/approvals/email.py
Some other email template context vars may need to be checked
=> missing approval added to context for aup vessel sold email

mooringlicensing/components/payments_ml/models.py, mooringlicensing/components/proposals/models.py, mooringlicensing/components/proposals/utils.py
- Fees are calculated by direct multiplication to vessel length when set to incremental (instead of per metre)
- Fee deductions are based on previous vessel lengths on the approval within the same year/season (instead of previous amount paid)
- fixed a problem with non-migrated mooring license DOT check
Fee deduction may require review
=> Fee calc change

mooringlicensing/components/proposals/utils.py, mooringlicensing/templates/mooringlicensing/emails_2/email_30.html, mooringlicensing/templates/mooringlicensing/emails_2/email_30.txt, mooringlicensing/templates/mooringlicensing/emails_2/email_30_future.html, mooringlicensing/templates/mooringlicensing/emails_2/email_30_future.txt
Changed email template as specified in issue - using conditions within the template
Also change the future email version of the same template based on common elements.
Fixed a number of unintended surrender blocks for related AUPs on ML (similar to previous fixes for the same issue)
=> Surrender email change

mooringlicensing/components/approvals/models.py, mooringlicensing/components/main/utils.py, mooringlicensing/components/proposals/utils.py
- Added extra columns to sticker printing batch file
- Changed sticker printing batch file from xlsx to csv
- Fixed white info column in stinking printing batch file from never populating
- Fixed syntax error when validating non-migrated ML submissions
- Added validation to ensure AUPs have at least one site licensee on submission (unless RIA auth selected)
=> ML Changes and Fixes

mooringlicensing/components/approvals/models.py, mooringlicensing/management/commands/change_user_email.py
Validation rules added for merging records from one user to another
The rules will ensure that users will not have records merged that would otherwise not be allowed through ordinary means
The rules are comprehensively enforced, but usage should be accompanied by careful examination of user records prior to merging email change
=> Email change validation rules
