mooringlicensing/components/compliances/api.py
mooringlicensing/components/proposals/api.py
mooringlicensing/helpers.py

- System actually handles most situations via:
raise Http404('No %s matches the given query.' %queryset.model._meta.object_name)
- Added additional check to ensure submitter and applicant emails match.

Graeme Enhancement

---

mooringlicensing/views.py

Non-internal users can no longer access the management command page

Management Command Security Fix

---

mooringlicensing/components/approvals/api.py
mooringlicensing/components/approvals/email.py
mooringlicensing/components/approvals/models.py
mooringlicensing/components/compliances/api.py
mooringlicensing/components/compliances/email.py
mooringlicensing/components/compliances/models.py
mooringlicensing/components/main/models.py
mooringlicensing/components/main/process_document.py
mooringlicensing/components/organisations/api.py
mooringlicensing/components/organisations/models.py
mooringlicensing/components/proposals/api.py
mooringlicensing/components/proposals/email.py
mooringlicensing/components/proposals/models.py
mooringlicensing/components/proposals/serializers.py
mooringlicensing/components/users/api.py
mooringlicensing/components/users/models.py
mooringlicensing/components/users/utils.py
mooringlicensing/urls.py
mooringlicensing/views.py

Completed work to move file storage to private media and ensuring only authorised users can access certain files.
Internal users can access all files, External users can access files if it is accessible via link on the web interface and they are the submitter of the record to which the file pertains.

File auth fix

---

requirements.txt

Using a ~ now to avoid going straight to 5.1

Django ~= 5.0.7

---

mooringlicensing/components/proposals/models.py
mooringlicensing/components/proposals/serializers.py
mooringlicensing/frontend/mooringlicensing/src/components/internal/proposals/proposal_approval.vue

Auto Approve checks now include checking the application's vessel's weight (if applicable), draft, and length to each of the moorings specified and/or previously assigned.

Auto approver vessel mooring specification checks

---

mooringlicensing/components/payments_ml/admin.py
mooringlicensing/components/payments_ml/models.py

Minor adjustments to fee constructor code to allow for editing/removal.
Some more fixes may be required subject to further investigation - these fixes should allow for some blockers for testing to be remedied.

Fee con fixes

---

mooringlicensing/components/approvals/api.py
mooringlicensing/components/approvals/models.py
mooringlicensing/components/approvals/serializers.py
mooringlicensing/components/proposals/models.py
mooringlicensing/components/users/utils.py
mooringlicensing/frontend/mooringlicensing/src/components/common/table_stickers.vue
mooringlicensing/utils/mooring_licence_migrate_pd.py

Changes to migration script including:
- Missing sticker numbers are accounted for with migrated AAPs, ready to be exported with application set to "printing_sticker"
- Where available, actual issue/lodgement dates have been migrated
- Approval history implemented for all applications, with retroactive file assignment during migration
- Application fees implemented
A number of dates, for applications and stickers, are still not available for migration. Further work may be required to account for these values.
Iexact for email user queries left out for now pending general fix (both on ML and ledger).

Migration Changes

---

mooringlicensing/frontend/mooringlicensing/src/components/common/swap_moorings_modal.vue
mooringlicensing/frontend/mooringlicensing/src/components/external/dashboard.vue
mooringlicensing/frontend/mooringlicensing/src/components/external/dcv/dcv_admission.vue
mooringlicensing/frontend/mooringlicensing/src/components/external/routes/index.js
mooringlicensing/frontend/mooringlicensing/src/components/forms/section_toggle.vue
mooringlicensing/frontend/mooringlicensing/src/components/internal/proposals/proposal_approval.vue
mooringlicensing/frontend/mooringlicensing/src/components/internal/stickers/dashboard.vue

Fixed JS errors - including one that prevents the external dashboard panels from opening

Minor JS fixes

---

mooringlicensing/components/approvals/api.py
mooringlicensing/components/approvals/models.py

Removed permission blocking applicant's from surrendering and applied a check in the model function.

WL surrender fix

---

mooringlicensing/components/approvals/models.py
mooringlicensing/components/payments_ml/models.py
mooringlicensing/components/proposals/utils.py
mooringlicensing/settings.py

Number of MLA testing fixes.
MLA testing is not complete, but some issues found in dev/uat have been addressed with these changes.

MLA auto approve fixes

---

mooringlicensing/components/approvals/models.py
mooringlicensing/components/proposals/email.py
mooringlicensing/components/proposals/models.py
mooringlicensing/components/proposals/serializers.py

Number of fixes pertaining to MLA renewals, as well some minor amendment related fixes for all application types.
The merge request concludes one full round of testing auto-approval and sticker printing workflows. Another round of dev testing should be conducted prior to releasing for UAT.
Some issues related but not directly affecting the tested workflows still need to be resolved.

MLA renewal fixes

---

mooringlicensing/components/approvals/api.py
mooringlicensing/components/approvals/email.py
mooringlicensing/components/compliances/email.py
mooringlicensing/components/emails/utils.py
mooringlicensing/components/proposals/email.py
mooringlicensing/components/proposals/utils.py
mooringlicensing/components/users/utils.py
mooringlicensing/utils/mooring_licence_migrate_pd.py

Minor fix to address issue of multiple ledger accounts with the same email (in different cases) that are all active. This was causing waiting list holder details to not be displayed properly.

Added order by to all email user queries

---

mooringlicensing/components/approvals/api.py
mooringlicensing/components/proposals/api.py
mooringlicensing/frontend/mooringlicensing/src/components/common/table_approval_to_be_endorsed.vue
mooringlicensing/frontend/mooringlicensing/src/components/common/table_approvals.vue
mooringlicensing/frontend/mooringlicensing/src/components/common/table_proposals.vue

Fixed ordering on endorsements table
Also fixed ordering/search bug for main proposal/approval tables

Order search fix

---

mooringlicensing/components/approvals/admin.py
mooringlicensing/components/proposals/admin.py
mooringlicensing/components/proposals/api.py
mooringlicensing/settings.py

Updated admin interfaces to prevent long loading times. Mostly just changing certain fields to read only so they don't pull the entire table down.
Fixed mooring record total display.
Fixed hiding billing address for system user interface.

Admin cleanup and minor fixes

---

mooringlicensing/utils/mooring_licence_migrate_pd.py

Fixed various reported migration issues:
- WL issue date change to "date_applied"
- Fixed date TZ inconsistency
- Fixed ML vessel users being falsely used to create AUP
- Fixed AUP missing because the same vessel was used for an ML (on a different mooring)
- Ownership percentage is now migrated as blank if not provided (or below 25)

Migration fixes 

---

mooringlicensing/components/payments_ml/utils.py
mooringlicensing/components/proposals/models.py
mooringlicensing/frontend/mooringlicensing/src/components/common/vessels.vue
mooringlicensing/frontend/mooringlicensing/src/components/internal/proposals/proposal_requirements.vue

- Added vessel length validation for mooring amendments at approve propose stage
- Company ownership form inputs display for ownership amendments
- Vessel rego no properly displayed in new application invoices
- Add condition works for assessor
-

Misc fixes

---

mooringlicensing/components/proposals/models.py
mooringlicensing/utils/mooring_licence_migrate_pd.py

Fixed WLA auto approve logic to account for recently overhauled vessel details storage

Wla auto approve

---

.devcontainer/devcontainer.json
mooringlicensing/components/payments_ml/models.py
mooringlicensing/components/proposals/models.py

Updated devcontainer.json to run latest postgres 
Fixed fee constructor query that broke due to postgres version change
Fixed validation for non-wla applications when current approval proposal are missing vessel ownership records

database update fix + validation fix

---

mooringlicensing/components/approvals/serializers.py
mooringlicensing/utils/mooring_licence_migrate_pd.py

- Fixed bad indexing that prevent more than 2 mooring license vessels from being migrated
- Increased validation on AUP moorings to prevent moorings beings added to AUPs when the holder is the mooring licensee
- Fixed phone number serialiser/display issue for booking/permits list on mooring page

Migration fixes

---

mooringlicensing/components/proposals/models.py

- fixed None error during largest vessel calculation
- fixed vessel ownership changed check for MLA AA
- removed keep current vessel check for MLA AA (not applicable pre-approval)

unchanged renewed mla are auto approved

---

mooringlicensing/components/compliances/api.py
mooringlicensing/components/proposals/api.py
mooringlicensing/components/proposals/models.py

- Fixed AUP Vessel Record Sale
- Fixed Compliance Dashboard search
- Fixed AUP requested moorings being added regardless of being checked on approval

Misc fixes 

---

mooringlicensing/components/payments_ml/models.py

Simplify fee calculation with incremental size categories (per request)
instead of factoring in previous vessel size categories during calculation, incremental fees are calculated on their own using the entire vessel length

Fee Calc Adjustment

---

mooringlicensing/components/main/models.py
mooringlicensing/components/main/utils.py

Added script tag removal for fields that allow some tags (such as richtext)
Implemented an exclude list kwarg that is still subject to script tag removal
Fixed tag removal to return None if provided value is None
Added a kwarg for fields that should be not be changed through sanitisation

Sanitise fields additions

---

mooringlicensing/components/main/utils.py
requirements.txt

script tag remove now case insensitive
upgraded to 5.2, replaced django-cron package

Django 5.2 and minor sanitise adjustment

---

mooringlicensing/components/approvals/models.py
mooringlicensing/components/payments_ml/views.py
mooringlicensing/components/proposals/models.py

Better payment error handling
Fixed float conversion issue for certain invoices where rounding is disabled

Payment error handling

---

mooringlicensing/components/proposals/models.py
mooringlicensing/management/default_data_manager.py

- replaced default sticker contact email with better placeholder
- fixed swap mooring approval through bypassing payment required function

minor fixes

---

mooringlicensing/components/approvals/email.py
mooringlicensing/components/proposals/email.py
mooringlicensing/components/proposals/serializers.py
mooringlicensing/components/users/utils.py
requirements.txt

Going back to Django 5.1.8
Also some minor file fixes

Django 5.1.8

---

mooringlicensing/components/proposals/templates/mooringlicensing/mgt-commands.html
mooringlicensing/context_processors.py
mooringlicensing/templates/mooringlicensing/base.html

also added git commit hash to context processor

Management command for run job queue (generate and email reports)

---

mooringlicensing/components/proposals/utils.py

Migrated vessel ownership records don't have dot names recorded.
We skip the check for dot names when checking migrated approvals but enforce the check on amendments.
Renewed approvals which have those vessel ownership records carried over may require further intervention.

Accommodate missing dot names in migrated records

---

mooringlicensing/components/proposals/email.py
mooringlicensing/frontend/mooringlicensing/src/components/common/table_proposals.vue
mooringlicensing/frontend/mooringlicensing/src/components/common/table_vessels.vue

- Removed unused add vessel button from search user page
- Fixed incorrect email template value
- Added discard for draft applications for internal users

ML Misc fixes 

---

mooringlicensing/components/proposals/models.py

Fixed AUP validation to use correct model when retrieving mooring dimensions (different depending on previously or newly added moorings)

Vessel check fix
